[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["guaranteed_delivery"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "guaranteed_delivery"
  org = "choreointegrationteam"
  version = "3.1.1"

